import { describe, it, expect } from 'vitest';
import { DEFAULT_INVOICE_FOOTER } from './InvoicesList';

describe('Invoice PDF Branding', () => {
  it('uses TimeSage in the default generated PDF footer', () => {
    expect(DEFAULT_INVOICE_FOOTER).toBe('Generated by TimeSage');
  });
});
